version: "2"

services:

  mariadb:
    image: mariadb:latest 
    restart: always
    networks:
      - network1
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network1
    links:
      - mariadb:db
    labels:
      - "traefik.backend=pma"
      - "traefik.frontend.rule=Host:pma.dodeeric.be"

  omeka:
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest
    restart: always
    networks:
      - network1
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
    labels:
      - "traefik.backend=omeka"
      - "traefik.frontend.rule=Host:omeka.dodeeric.be"  

  gramps:
    image: httpd:latest
    restart: always
    networks:
      - network1
    volumes: 
      - gramps:/usr/local/apache2/htdocs
    labels:
      - "traefik.backend=gramps"
      - "traefik.frontend.rule=Host:gramps.dodeeric.be"

  traefik:
    image: traefik:latest
    restart: always
    networks:
      - network1
    command: --web --docker --docker.domain=dodeeric.be
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml

volumes:
  mariadb:
  omeka:
  gramps:

networks:
  network1:  
