version: "2"

services:
  mariadb:
    image: mariadb:latest 
    restart: always
    networks:
      - network1 
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  omeka:
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest 
    restart: always
    networks:
      - network1 
    ports:
      - "80:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume

volumes:
  mariadb:
  omeka:

networks:
  network1:  
